### PR TITLE
fix: Color labeled as unknown #58

### PR DESCRIPTION
**Pull request by iamoghenerukevwe**
Color labelled as unknown #58

### CODE REVIEW

**Comment by alexdanilowicz** [comment]
Hey thanks Michael! @iamoghenerukevwe 

Good debugging here, could you explain why the hsl changes fix it?

I think it's better, but I still get an unknown if you regenerate a couple of times: 
image

This is for hex #ea7a96. I need to take a closer look. But perhaps you'll know the bug right away?

**Comment by prichter** [comment]
OK, did some testing and I think the problem here is that tinycolor.toHSL() returns values as hue, saturation, lightness _in that order_, but the `nameThatColor` method takes parameters in _hue, lightness, saturation_ order.  I suspect that this is causing some out of range values to be assessed, resulting in "Unknown" color.

**Comment by prichter** [comment]
OK, I have identified some gaps in the `nameThatColor` functionality.  The edge case is where `tinycolor().toHsl()` returns decimal values for HSL that are between the boundary conditions in the 'if' cases.  For example, if hue of 54.54 is returned, if falls between the <=54 and >=55 cases (brown/orange vs brown/yellow cases in `nameThatColor`).
The crux of the matter is that tinycolor returns decimal values, but `nameThatColor` expects integer values.

**Comment by alexdanilowicz** [comment]
nice @prichter — thanks for chiming in. Really well explained. Excellent. Do you know the ultimate fix? Feel free to push it up

**Comment by alexdanilowicz** [comment]
Great teamwork here.

**Comment by iamoghenerukevwe** [comment]
Thanks @prichter for so coherently putting it, I discovered that boundary conditions in the if statements were causing the error of "Unknown" and to resolve the issue  would simply be to make sure that there are no gaps, in the values used for the if statements. I'll just hold until @prichter is done, then I can add in more color names.

**Comment by alexdanilowicz** [comment]
image

This also seems messed up (this is on `main`). I'd expect Yellow vs Green for `#f1f30d`. 

Screen Shot 2023-03-14 at 3 21 33 PM

Same with red vs pink for `#f30d55`

I wish we could use `tinycolor.toName()` from https://github.com/bgrins/TinyColor but it seems that returns false for hex values. I bring up the above bugs in case the algo as a whole needs to be fixed, instead of just patching it

**Comment by prichter** [comment]
@alexdanilowicz certainly.  I'll work on this next...

**Comment by alexdanilowicz** [comment]
Closing this in favor of https://github.com/Mirrorful/mirrorful/pull/182

Nice work, @prichter !

**Pull request closed without merging**
