### PR TITLE
Update all examples to be on latest version of Mirrorful

### LINKED ISSUE #269: Update all examples to be on the latest version of mirrorful
For example, CRA is behind.

### PR DESCRIPTION
**Pull request by nyeno**
In response to the Issue 269 which is to Update the example files to be the latest version of Mirrorful. I added information to the README file to help users get started with the create-react-app

---

Fixes #269

### CODE REVIEW

**Comment by alexdanilowicz** [comment]
Hi @nyeno thanks! We also need to update Mirrorful to version 5.0.6 (the latest) here in the package.json: https://github.com/Mirrorful/mirrorful/blob/main/examples/create-react-app/package.json#L39

**Comment by alexdanilowicz** [comment]
Related to: https://github.com/Mirrorful/mirrorful/issues/269

**Comment by nyeno** [comment]
Hi @alexdanilowicz I have updated all the example to the latest version of mirrorful. I also ran npx mirrorful after updating on each example to assert that it works well. It does work without any issues on each example.
image

**Comment by alexdanilowicz** [comment]
@nyeno amazing, thank you so much! will merge this in tomorrow.

**Comment by nyeno** [comment]
You are welcome @alexdanilowicz It was a pleasure

**Pull request merged**
