### PR TITLE
fix: center align the 'You are not logged in' popover on sm screens

### LINKED ISSUE #482: Mobile Responsiveness: Center Align the 'You are not logged in' alert
image

### PR DESCRIPTION
**Pull request by Pranav2612000**
Fixes #482

### CODE REVIEW

**Comment by Pranav2612000** [comment]
small mobiles
image

large mobiles
image

ipad
image

1024px
image

1440px
image

**Comment by alexdanilowicz** [comment]
@Pranav2612000 very nice. will merge tmrw.

**Comment by agupta0001** [comment]
Just want to confirm, if it's expected to show notification on left side for 1440px.

**Comment by Pranav2612000** [comment]
Yeah. That was the previous behaviour as well. @alexdanilowicz Do we want it to change the behaviour?

**Comment by alexdanilowicz** [comment]
@Pranav2612000. nice work. and re: 1440px, it's fine as is. Thanks!

**Pull request merged**
